### PR TITLE
fix: support yarn berry

### LINKED ISSUE #43: Getting an error while publishing the packages when using yarn 2
We use gitpkg for publishing the internal packages as git tags, it works well for a project that uses yarn 1.

But on a project that uses Yarn 2 , getting an error while `gitpkg` tries to publish the tags. Can we support `gitpkg` when using yarn 2.

```
Stderr Status: gitpkg publish v1.0.0-beta.2

Stderr Status: lerna ERR! gitpkg publish stderr:

Stderr Status: - Processing...
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/projectyarn2/packages/package-xyz/package-xyz-v0.2.0.tgz'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:126:14
    at FSReqCallback.oncomplete (fs.js:180:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/projectyarn2/packages/package-xyz/package-xyz-v0.2.0.tgz'
}
```

### PR DESCRIPTION
**Pull request by appsforartists**
Adding support for the default package name in Berry (`package.tgz`) is the simplest fix.

Alternatively, we could detect the yarn lineage and use `--filename` (classic) or `--out` (berry) to use the same package name across clients.

Fixes #43

---

I haven't used jest before, so getting the tests to work has been a chore.  I was able to adapt your `get-npm-client` test to work for `get-yarn-lineage`, but I don't know the right way to mock a local module to update the `get-npm-client` test.

### CODE REVIEW

File: src/tasks/Publish/get-npm-client.js [hunk 1]
```diff
@@ -1,24 +1,8 @@
...
-let cacheNpmClient = null;
+import getYarnLineage from './get-yarn-lineage';
 
 export default async function getNpmClient() {
-  if (cacheNpmClient) {
-    return cacheNpmClient;
-  }
-
-  const useYarn = await shouldUseYarn();
+  const useYarn = await Boolean(getYarnLineage());
```
Comment (ramasilveyra) [inline src/tasks/Publish/get-npm-client.js:4]: This should be:
```suggestion
  const useYarn = Boolean(await getYarnLineage());
```

otherwise it will always be true?
Screen Shot 2022-06-17 at 17 23 09

Comment (appsforartists) [reply src/tasks/Publish/get-npm-client.js]: Good catch!  Fixed (and added a test).

**Comment by ramasilveyra** [comment]
Thank you!

**Comment by ramasilveyra** [comment]
released on [v1.0.0-beta.4](https://github.com/ramasilveyra/gitpkg/blob/master/CHANGELOG.md#100-beta4-2022-06-17)
